In [5]:
import torch
batch_1 = torch.randn(10,3,4)
batch_2 = torch.randn(10,4,5)

In [6]:
batch_1

tensor([[[ 1.6743, -0.8272, -0.3609,  0.7542],
         [ 0.5323, -1.1588,  1.9887, -0.3474],
         [ 1.9591,  0.7905, -0.1633, -1.0724]],

        [[ 2.0124,  0.6733, -0.5478,  0.7431],
         [-0.6953,  0.6167,  2.4518, -0.4400],
         [ 1.4976,  0.0760, -0.2469, -1.4151]],

        [[-0.3367,  0.2401, -0.1449,  2.0110],
         [-0.3922, -0.1357, -0.2414, -0.7573],
         [ 2.6205,  1.4139, -0.7993, -0.3800]],

        [[-1.4319, -0.0677,  1.0657, -1.2914],
         [ 1.0597, -1.3503, -0.3300,  0.8480],
         [ 1.0508,  0.5948, -0.3223, -0.8292]],

        [[ 0.1860, -0.3744,  1.4325,  0.6499],
         [ 0.4303,  1.2764, -1.0879, -0.8163],
         [-1.2706,  2.1664, -0.4768,  0.0133]],

        [[-1.2981,  1.8120, -0.4613, -0.9221],
         [-0.5122,  0.5270, -2.2312,  0.1325],
         [-0.7020, -0.8781,  0.2396, -0.2424]],

        [[-0.1011, -0.3292, -0.2176, -0.5015],
         [ 0.0395, -0.0826, -0.3189,  0.2788],
         [-0.1910, -0.6419,  0.1220,  1.2180]],


In [7]:
result = torch.bmm(batch_1,batch_2)
result

tensor([[[-2.3823, -0.8592,  2.9826, -3.4849, -0.8986],
         [ 2.8802,  3.5289, -0.6811, -0.6005, -1.2251],
         [ 1.9353,  0.2378,  0.6514,  0.9045,  0.8329]],

        [[-0.7346, -1.5957,  0.1700, -3.4987, -2.0320],
         [-0.8411,  5.0411,  0.1932,  3.8514,  1.5175],
         [-0.9290, -1.3251,  1.0748, -2.9015, -2.1409]],

        [[-1.1047,  0.8052,  3.3383, -2.1602, -1.5278],
         [ 0.0897, -0.0083, -2.3502,  0.4467,  0.4129],
         [-4.7520,  1.2016,  2.4772,  6.5534,  1.2486]],

        [[-1.5291, -1.1849, -0.9888,  3.4016, -5.5225],
         [ 3.0759, -1.8484,  1.4577, -1.1097,  4.0741],
         [ 0.9937,  3.6306,  1.3028, -3.4389, -0.1400]],

        [[-0.0510, -3.2663,  0.1811,  0.2530,  0.3498],
         [-0.9202,  2.1356, -0.8940, -1.2532, -0.7563],
         [ 2.1388, -0.1662,  1.6198, -6.0431, -2.6430]],

        [[ 1.2410, -5.7289,  3.6741, -2.5091,  4.3891],
         [ 1.3305, -2.6598,  1.2871, -1.5959,  1.0365],
         [ 1.2228,  0.5009,  2.7455,  

In [8]:
result.shape

torch.Size([10, 3, 5])

In [ ]:
import torch

batch_size = 1 # 批量大小
seq_len = 3
input_size = 4
hidden_size = 2

cell = torch.nn.RNN(input_size = input_size, hidden_size = hidden_size)

dataset = torch.randn(seq_len,batch_size,input_size)
hidden = torch.zeros(batch_size,hidden_size) # h0

# 对dataset进行遍历，每次取出序列中的一个元素，即先取x1,再去x2,最后取x3
for idx,input in enumerate(dataset):
    print('=' * 20,idx,'='*20)
    print('Input size:',input.shape)
    
    hidden = cell(input, hidden) # cell中的hidden为上一次输出的隐层，等号左边的hidden为这一次的隐层。
    
    print('outputs size',hidden.shape)
    print(hidden)

## --------????--------

In [12]:
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from torch.autograd import Variable
from sklearn.metrics import mean_squared_error
data_csv =pd.read_csv("./data_input/data_rnn.csv", usecols=[1])
data_csv = data_csv.dropna()
dataset = data_csv.values
dataset = dataset.astype("float32")
scaler = MinMaxScaler()
dataset = scaler.fit_transform(dataset)
look_back = 30
def create_dataset(dataset, look_back):
    dataX, dataY = [], []
    for i in range(len(dataset) - look_back):
        a = [dataset[i: (i + look_back)]]
        dataX.append(a)
        dataY.append(dataset[i + look_back])
    return np.array(dataX), np.array(dataY)

dataX, dataY = create_dataset(dataset, look_back)
print(len(dataX))
print(len(dataY))
print(len(dataX[0]))
print(len(dataY[0]))
print((dataX[0],dataY[0]))

114
114
1
1
(array([[[0.01544401],
        [0.02702703],
        [0.05405405],
        [0.04826255],
        [0.03281853],
        [0.05984557],
        [0.08494207],
        [0.08494207],
        [0.06177607],
        [0.02895753],
        [0.        ],
        [0.02702703],
        [0.02123553],
        [0.04247104],
        [0.07142857],
        [0.05984557],
        [0.04054055],
        [0.08687258],
        [0.12741312],
        [0.12741312],
        [0.10424709],
        [0.05598456],
        [0.01930502],
        [0.06949806],
        [0.07915059],
        [0.08880308],
        [0.14285713],
        [0.11389962],
        [0.13127413],
        [0.14285713]]], dtype=float32), array([0.18339768], dtype=float32))


In [ ]:
len(dataX[0][0])

## --------????--------

In [30]:
import numpy as np
xx = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
xx.shape

(3, 3, 3)

In [31]:
xx[1:,:2,:2]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

In [9]:
import numpy as np
 
a = np.arange(8).reshape(1,1,4,2) # 或者 .reshape((1,1,4,2)) 也行
 
print ('原数组：')
print (a)
# 默认按行
 
print ('展开的数组：')
print (a.flatten())
 
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'F'))
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'A')) #'C' -- 按行，'F' -- 按列，'A' -- 原顺序

原数组：
[[[[0 1]
   [2 3]
   [4 5]
   [6 7]]]]
展开的数组：
[0 1 2 3 4 5 6 7]
以 F 风格顺序展开的数组：
[0 2 4 6 1 3 5 7]
以 F 风格顺序展开的数组：
[0 1 2 3 4 5 6 7]
