### 参考网址： https://www.runoob.com/numpy/numpy-array-manipulation.html

In [118]:
import numpy as np
xx = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
xx.shape

(3, 3, 3)

## 切片
##### 逐层索引，  该层从哪里开始（不写代表0）：到哪里结束（不包含该索引）（不写代表全部）：间隔多少（不写代表不间隔）

In [119]:
xx[1:,:2,1:2]

array([[[11],
        [14]],

       [[20],
        [23]]])

In [120]:
xx[::2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [121]:
xx[:,-1:,::-1]

array([[[ 9,  8,  7]],

       [[18, 17, 16]],

       [[27, 26, 25]]])

In [122]:
xx[...,-1:,::-1]  # 省略号与':' 等效

array([[[ 9,  8,  7]],

       [[18, 17, 16]],

       [[27, 26, 25]]])

In [123]:
z = np.zeros((2,2,2), dtype = [('x', 'i4'), ('y', 'i4')])  # x和y是两个字段，每个字段是一个整数{i4（int4）类型}，因此每个位置有两个0
print(z[0,0,0]['y'])
print(z[0][0][0]['x'])
print(z[0][0])

0
0
[(0, 0) (0, 0)]


##### np.asarray与np.array的主要区别在于，（默认情况下）将会copy该对象，而 np.asarray 除非必要，否则不会copy该对象。

## 花式索引

In [126]:
import numpy as np 
 
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  # 取出x[0,0]，x[1,1]，x[2,0]，更加灵活，能直接组成array的形式
print(y)
print(type(y))

[1 4 5]
<class 'numpy.ndarray'>


In [140]:
import numpy as np
x = np.array([11,22,33,44,55,66,77,88,99])
print(x)
# 一维数组读取指定下标对应的元素
print("-------读取下标对应的元素-------")
x2 = x[[0,3,2,5]] # 使用花式索引
print(x2) 
print(x[:4])
print(x2[1])
print(x[[-1,-3]])

[11 22 33 44 55 66 77 88 99]
-------读取下标对应的元素-------
[11 44 33 66]
[11 22 33 44]
44
[99 77]


In [142]:
import numpy as np 
x=np.arange(32).reshape((8,4))  # 或者 .reshape((8,4)) 也行
print(x)
print("-"*10)
print(np.ix_([1,5,7,2],[0,3,1,2]))  # 笛卡尔积关系
print("-"*10)
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
----------
(array([[1],
       [5],
       [7],
       [2]]), array([[0, 3, 1, 2]]))
----------
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [143]:
import numpy as np
 
a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
# 默认按行
 
print ('展开的数组：')
print (a.flatten())
 
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'F'))
print ('以 F 风格顺序展开的数组：')
print (a.flatten(order = 'A')) #'C' -- 按行，'F' -- 按列，'A' -- 原顺序

原数组：
[[0 1 2 3]
 [4 5 6 7]]
展开的数组：
[0 1 2 3 4 5 6 7]
以 F 风格顺序展开的数组：
[0 4 1 5 2 6 3 7]
以 F 风格顺序展开的数组：
[0 1 2 3 4 5 6 7]


### 返回数组的排序后的索引序列

In [147]:
import numpy as np 
 
x = np.array([8,  1,  5])  
print ('我们的数组是：')
print (x)
print ('对 x 调用 argsort() 函数：')
y = np.argsort(x)  
print (y)
print ('以排序后的顺序重构原数组：')
print (x[y])

我们的数组是：
[8 1 5]
对 x 调用 argsort() 函数：
[1 2 0]
以排序后的顺序重构原数组：
[1 5 8]


In [3]:
import numpy as np
x = [1,2,3,4,5,6,7,8,9,10]
s = np.array(x)
s_mod2equal0 = np.array(s%2 == 0)
s_mod2equal0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])