### https://blog.csdn.net/lemonbit/article/details/121586067

In [126]:
import torch

t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print("*-"*12)
print(t.ndim) #查看维度
print(t.shape) #查看形状
print(t.numel()) #查看元素个数

tensor([[1, 2, 3],
        [4, 5, 6]])
*-*-*-*-*-*-*-*-*-*-*-*-
2
torch.Size([2, 3])
6


### 变形

In [127]:
print(t.flatten())
print(t.reshape(1, 3, 2))
print(t.reshape((2, 3, 1)))

tensor([1, 2, 3, 4, 5, 6])
tensor([[[1, 2],
         [3, 4],
         [5, 6]]])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])


###  压缩与维度扩充

In [128]:
t = t.reshape((2, 3, 1))
print(t.shape)
t_s = t.squeeze(2) # 对第三个维度进行压缩, 若不填参数则压缩所有维度为1的维度
print(t_s)
print(t_s.shape)

torch.Size([2, 3, 1])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [129]:
t_s = t_s.unsqueeze(1)     # unsqueeze的作用是解压张量，给指定位置加上维数为一的维度，不能不填维度。
print(t_s)
print(t_s.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
torch.Size([2, 1, 3])


#### 二维张量索引

In [130]:
t2 = torch.arange(1, 17).reshape(4, 4)
print(t2)
print(t2[0, 1])
print(t2[0][1])  # t2[0,1]也可用t2[0][1]的表示。
print(t2[::2, ::2])
print(t2[::2][::2]) # 但是t2[::2, ::2]与t2[::2][ ::2]的索引结果就不同：（因为这种写法要 左结合, 相当于一直在取行，最后只能取出第一行）

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
tensor(2)
tensor(2)
tensor([[ 1,  3],
        [ 9, 11]])
tensor([[1, 2, 3, 4]])


#### 三维张量索引

In [131]:
t3 = torch.arange(1, 28).reshape(3, 3, 3)
print(t3)
print(t3[1, 1, 1])  # 索引第二个矩阵中的第二行、第二个元素
print(t3[1, ::2, ::2]) # 索引第二个矩阵，行和列都是每隔两个取一个

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])
tensor(14)
tensor([[10, 12],
        [16, 18]])


#### 张量的分割

In [132]:
t2 = torch.arange(12).reshape(4, 3)  # 创建一个4×3的矩阵
print(t2)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


##### 返回的张量tc的一个视图，不是新成了一个对象

In [133]:
tc = torch.chunk(t2, chunks = 3, dim = 0) # 在第0维度上分割成3块，因为无法等分，所以可能小于3块。
print(tc)
print(len(tc)) # 若原张量不能均分时，chunk不会报错，会返回次一级均分结果。

(tensor([[0, 1, 2],
        [3, 4, 5]]), tensor([[ 6,  7,  8],
        [ 9, 10, 11]]))
2


##### 与chunk函数不同的是，split第二个参数可以输入一个序列，表示按照序列数值分，序列各数值的和必须等于对应维度下形状分量的取值

In [134]:
tc2 = torch.split(t2, [1,2,1], dim = 0) 
print(tc2)
print(len(tc2))

(tensor([[0, 1, 2]]), tensor([[3, 4, 5],
        [6, 7, 8]]), tensor([[ 9, 10, 11]]))
3


#### 张量的拼接cat

In [135]:
a = torch.zeros(2, 3)
print(a)
b = torch.ones(2, 3)
print(b)
tcat1 = torch.cat([a, b], dim = 0)
tcat2 = torch.cat([a, b], dim = 1)
print("*-"*12)
print(tcat1) # 在第0维度上拼接，其他维度不变。0维上拼接后，形状变为(4, 3)
print(tcat1.shape)
print("*-"*12)
print(tcat2) # 在第1维度上拼接，其他维度不变。1维上拼接后，形状变为(2, 6)
print(tcat2.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
*-*-*-*-*-*-*-*-*-*-*-*-
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])
*-*-*-*-*-*-*-*-*-*-*-*-
tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])
torch.Size([2, 6])


In [136]:
tstack = torch.stack([a, b], dim = 0)
print(tstack) # 和拼接不同，堆叠不将元素拆分重装，而是将参与堆叠的对象分装到一个更高维度的张量里。
print(tstack.shape)
print("*-"*12)
tstack2 = torch.stack([a, b], dim = 2)
print(tstack2)
print(tstack2.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
*-*-*-*-*-*-*-*-*-*-*-*-
tensor([[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]])
torch.Size([2, 3, 2])
